export const mainData = {
  info: {
    kor_name: '조보화',
    eng_name: 'Bohwa Jo',
    email: 'jobong212@gmail.com',
  },
  work: [
    {
      id: 1,
      title: '중소기업 홈페이지',
      techs: ['html', 'css', 'javascript', 'jquery'],
      rep_url: 'http://www.hdmoo.com/',
      rep_image: '',
      start: '2015-10',
      end: '2016-02',
    },
    {
      id: 2,
      title: '대리주부',
      techs: ['html', 'css', 'javascript', 'jquery'],
      rep_url: 'http://www.daerijubu.com/',
      rep_image: '',
      start: '2016-03',
      end: '2016-07',
    },
    {
      id: 3,
      title: '홈스토리생활',
      techs: ['html', 'css', 'javascript', 'jquery'],
      rep_url: 'http://m.homesaeng.com/',
      rep_image: '',
      start: '2016-03',
      end: '2016-07',
    },
    {
      id: 4,
      title: '라마르조코코리아',
      techs: ['html', 'css', 'javascript', 'jquery'],
      rep_url: 'https://kr.lamarzocco.com/',
      rep_image: '',
      start: '2016-08',
      end: '2016-12',
    },
    {
      id: 5,
      title: '모드바',
      techs: ['html', 'css', 'javascript', 'jquery'],
      rep_url: 'http://modbar.co.kr/',
      rep_image: '',
      start: '2016-12',
      end: '2017-04',
    },
    {
      id: 6,
      title: '바리스타뉴스',
      techs: ['html', 'css', 'javascript', 'jquery'],
      rep_url: 'http://baristanews.co.kr/',
      rep_image: '',
      start: '2017-04',
      end: '2017-08',
    },
    {
      id: 7,
      title: '게티이미지뱅크 WEB',
      techs: ['html', 'css', 'javascript', 'jquery', 'Google Analytics', 'Google Tag Manager'],
      rep_url: 'https://www.gettyimagesbank.com/',
      rep_image: '',
      start: '2018-01',
      end: '2020-03',
    },
    {
      id: 7,
      title: '게티이미지뱅크 MOBILE',
      techs: ['html', 'css', 'javascript', 'jquery', 'Google Analytics', 'Google Tag Manager'],
      rep_url: 'https://m.gettyimagesbank.com/',
      rep_image: '',
      start: '2018-01',
      end: '2018-06',
    },
    {
      id: 8,
      title: '엔터프라이즈 게티이미지',
      techs: ['html', 'css', 'javascript', 'jquery', 'Google Analytics', 'Google Tag Manager'],
      rep_url: 'https://enterprise.gettyimageskorea.com/',
      rep_image: '',
      start: '2019-04',
      end: '2020-03',
    },
    {
      id: 9,
      title: '게티이미지 코리아',
      techs: ['html', 'css', 'javascript', 'jquery', 'Google Analytics', 'Google Tag Manager'],
      rep_url: 'https://mbdrive.gettyimageskorea.com/',
      rep_image: '',
      start: '2018-01',
      end: '2020-03',
    },
    {
      id: 10,
      title: '솔드아웃 소개 페이지',
      techs: ['html', 'css', 'javascript', 'jquery'],
      rep_url: 'https://soldout.co.kr/',
      rep_image: '',
      start: '2020-03',
      end: '2020-04',
    },
    {
      id: 11,
      title: '솔드아웃 관리자 페이지',
      techs: ['Vue.js', 'scss', 'html'],
      rep_url: 'https://admin.soldout.co.kr',
      rep_image: '',
      start: '2020-03',
      end: '',
    },
    {
      id: 12,
      title: '솔드아웃 래플 페이지',
      techs: ['Vue.js', 'scss', 'html'],
      rep_url: 'https://svc.soldout.co.kr/web/product/raffle/lists',
      rep_image: '',
      start: '2020-06',
      end: '2020-08',
    },
    {
      id: 13,
      title: '솔드아웃 App 웹뷰페이지',
      techs: ['Vue.js', 'scss', 'html'],
      rep_url: 'https://svc.soldout.co.kr/web/product/web_product/item_detail/11112',
      rep_image: '',
      start: '2021-03',
      end: '',
    },
    {
      id: 14,
      title: '솔드아웃 Web 페이지',
      techs: ['Vue.js', 'Nuxt.js', 'scss'],
      rep_url: 'https://web.soldout.co.kr/',
      rep_image: '',
      start: '2021-06',
      end: '',
    },
    {
      id: 15,
      title: '솔드아웃 마켓 웹뷰 페이지, 관리자 페이지',
      techs: ['Vue.js', 'Nuxt.js', 'Typescript', 'scss'],
      rep_url: 'https://web.soldout.co.kr/',
      rep_image: '',
      start: '2021-10',
      end: '',
    },
  ],
  tech: [
    'HTML', 'CSS', 'SCSS', 'Vue.js', 'Nuxt.js', 'TypeScript', 'React.js',
  ]
}
